### ISSUE TITLE
Poll metrics failure on Docker container.

### ISSUE THREAD

**Issue by bluebob** [logzio/jmx2graphite#12]
I'm getting the following error with the Docker container:
```
2017-02-09 13:55:24 INFO  MetricsPipeline:40 - Found 779 metric beans. Time = 85ms, for 2017-02-09T13:55:00.000+0000
2017-02-09 13:55:24 WARN  MetricsPipeline:54 - Failed polling metrics from client (class io.logz.jmx2graphite.JolokiaClient): Failed reading beans from Jolokia. Error = C
an not deserialize instance of java.util.ArrayList out of START_OBJECT token
 at [Source: java.io.ByteArrayInputStream@7b7427b2; line: 1, column: 1]
2017-02-09 13:55:24 ERROR MetricsPipeline:77 - Unexpected error occured while polling and sending. Error = null
java.lang.NullPointerException
	at io.logz.jmx2graphite.GraphiteClient.sendMetrics(GraphiteClient.java:97) ~[jmx2graphite-1.1.1.jar:?]
	at io.logz.jmx2graphite.MetricsPipeline.sendToGraphite(MetricsPipeline.java:101) ~[jmx2graphite-1.1.1.jar:?]
	at io.logz.jmx2graphite.MetricsPipeline.pollAndSend(MetricsPipeline.java:65) ~[jmx2graphite-1.1.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

System is a RHEL7 with Java reported as
```
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
```

And Jolokia (running on the same host) is v1.3.5

_Any suggestions how to fix?_

**Comment by bluebob** [comment]
Just checked that it wasn't the container by doing a source build (following the instructions given using gradlew) and get the same error message.

**Comment by asafm** [comment]
Sorry for the late reply.
I've noticed I've only printing the exception (cause) in case the logging
is in DEBUG for io.logz.jmx2graphite.MetricsPipeline

Could you please run it with logback.xml set for DEBUG for this class?

**Comment by bluebob** [comment]
Unfortunately not a Java dev, but I had a go, output is
[jmx2graphite.txt](https://github.com/logzio/jmx2graphite/files/777266/jmx2graphite.txt)

**Comment by asafm** [comment]
@bluebob That was very helpful. I still have one missing piece of information. JMX2Graphite first runs an HTTP request to Jolokia to get the list of available metric beans. You can see he got it: 
```
17/02/15 14:05:36 INFO jmx2graphite.MetricsPipeline: Found 790 metric beans. Time = 715ms, for 2017-02-15T14:05:30.000+0000
```

Next it run a POST request to Jolokia, in the body it writes all the metric beans he got before. The response body is supposed to be an Array of JSON object, one per metric. From some reason, the response body is a single JSON Object thus you see this exception:
```
Can not deserialize instance of java.util.ArrayList out of START_OBJECT token
```

I've pushed a commit to jmx2graphite and adds trace messages printing the request body and response body in TRACE log level.

Can you please do a git pull, build from source, set log level to TRACE, and paste back the result? Sorry for the inconvenience.

**Comment by bluebob** [comment]
Sorry for delay, log file (a lot larger!) attached.
[jmx2graphite112.txt](https://github.com/logzio/jmx2graphite/files/779956/jmx2graphite112.txt)

**Comment by asafm** [comment]
Weird. The response from Jolokia even though the status code is 200. I can get around that, but still Jolokia fails. What version of Jolokia are you using ?

**Comment by bluebob** [comment]
Jar running claims to be "jolokia-jvm-1.3.5-agent". Host is RHEL7.2

**Comment by asafm** [comment]
@bluebob I managed to track down the bug. It's in Jolokia JVM Agent. I've opened a bug for them here: rhuss/jolokia#305. 
It is caused if your JVM Agent was started in debug mode. How does your `-javaagent` command argument looks like?

**Comment by bluebob** [comment]
Sorry for delay in replying. Sure enough the JOLOKIA_OPTS setting I was using was "--debug". I've switched that to "--verbose" and jmx2graphite seems to be working fine now. Now all I've gotta do is turn off all that trace output... :)

**Comment by asafm** [comment]
Can this issue be closed?

**Comment by bluebob** [comment]
Oops, yes. Thanks. :)
