### ISSUE TITLE
Error HTTP 403 Code when accessing Jolokia URL 

### ISSUE THREAD

**Issue by harpo** [logzio/jmx2graphite#17]
Hi,
I want to monitor Spring Boot applications but the following issue occurs.

I have a Spring Boot application inside a Docker Swarm. The Jolokia Endpoint is functional:

`curl http://10.xxx.xx.x:10210/jolokia/list `
Curl shows all availabe metrics

I started jmx2graphite like this:
`docker run -i -t -d --name jmx2graphite -e "JOLOKIA_URL=http://10.xxx.xx.x::10210/jolokia/" -e "SERVICE_NAME=servicex" -e "GRAPHITE_HOST=graphite" -e "GRAPHITE_PROTOCOL=tcp" -e "GRAPHITE_PORT=2003"   -v /var/log/jmx2graphite:/var/log/jmx2graphite --rm=true logzio/jmx2graphite `

/var/log/jmx2graphite shows a 403 Http error code:

```
2017-10-23 15:40:07 INFO  MetricsPipeline:40 - Found 145 metric beans. Time = 63ms, for 2017-10-23T15:40:00.000+0000
2017-10-23 15:40:07 ERROR MetricsPipeline:77 - Unexpected error occured while polling and sending. Error = Failed reading beans from jolokia. Response = HTTP/1.1 403
java.lang.RuntimeException: Failed reading beans from jolokia. Response = HTTP/1.1 403
        at io.logz.jmx2graphite.JolokiaClient.getMetrics(JolokiaClient.java:88) ~[jmx2graphite-1.2.0.jar:?]
        at io.logz.jmx2graphite.MetricsPipeline.poll(MetricsPipeline.java:45) ~[jmx2graphite-1.2.0.jar:?]
        at io.logz.jmx2graphite.MetricsPipeline.pollAndSend(MetricsPipeline.java:63) ~[jmx2graphite-1.2.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
/var/log/jmx2graphite/jmx2graphite.log                                                                        

```

I checked if I was able to GET the jolokia endpoint from inside the jmx2graphite container and it worked fine:

```
docker exec -it jmx2graphite /bin/bash 

# curl http://10.201.35.2:10210/jolokia/list
{"request":{"type":"list"},"value":{"java.util.logging":{"type=Logging":{"op":{"getLoggerLevel":{"args":[{"name":"p0","type":"java.lang.String","desc":"p0"}],"ret":"java.lang.String","desc":"getLoggerLevel"},"getParentLoggerName":{"args":[{"name":"p0","type":"java.lang.String","desc":"p0"}],"ret":"java.lang.String","desc":"getParentLoggerName"},"setLoggerLevel":{"args":[{"name":"p0","type":"java.lang.String","desc":"p0"},{"name":"p1","type":"java.lang.String","desc":"p1"}],"ret":"void","desc":"setLoggerLevel"}},"attr":{"LoggerNames":{"rw":false,"type":"[Ljava.lang.String;","desc":"LoggerNames"},"ObjectName":{"rw":false,"type"
```

Why is it showing the 403 code in the log?

**Comment by asafm** [comment]
That’s very strange.
Two pieces of information are needed:
1. Turn TRACE level on for jmx2graphite, specifically io.logz.jmx2graphite.JolokiaClient

2. Can you show the jolokia java agent arguments you have set in your Spring boot application?
