### ISSUE TITLE
listening only /list/java.lang beans

### ISSUE THREAD

**Issue by blka** [logzio/jmx2graphite#18]
Hi, i would like to export a part of a whole jolokia tree, at this moment it's java.lang:*
i am able to change this url in JolokiaClient.java and recompile, but then i'm getting:
`java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at io.logz.jmx2graphite.JolokiaClient.extractMetricsBeans(JolokiaClient.java:137) ~[jmx2graphite-1.2.0.jar:?]
        at io.logz.jmx2graphite.JolokiaClient.getBeans(JolokiaClient.java:65) ~[jmx2graphite-1.2.0.jar:?]
        at io.logz.jmx2graphite.MetricsPipeline.poll(MetricsPipeline.java:39) ~[jmx2graphite-1.2.0.jar:?]
        at io.logz.jmx2graphite.MetricsPipeline.pollAndSend(MetricsPipeline.java:63) ~[jmx2graphite-1.2.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2017-10-25 06:51:01 DEBUG JolokiaClient:50 - Retrieving /list/java.lang of bean from Jolokia (http://127.0.0.1:8080/jolokia/)...
2017-10-25 06:51:05 DEBUG JolokiaClient:55 - GET /list/java.lang from jolokia took 3638 ms
2017-10-25 06:51:05 ERROR MetricsPipeline:77 - Unexpected error occured while polling and sending. Error = java.lang.String cannot be cast to java.util.Map
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at io.logz.jmx2graphite.JolokiaClient.extractMetricsBeans(JolokiaClient.java:137) ~[jmx2graphite-1.2.0.jar:?]
        at io.logz.jmx2graphite.JolokiaClient.getBeans(JolokiaClient.java:65) ~[jmx2graphite-1.2.0.jar:?]
        at io.logz.jmx2graphite.MetricsPipeline.poll(MetricsPipeline.java:39) ~[jmx2graphite-1.2.0.jar:?]
        at io.logz.jmx2graphite.MetricsPipeline.pollAndSend(MetricsPipeline.java:63) ~[jmx2graphite-1.2.0.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
`
could you help me with this?

**Comment by asafm** [comment]
The response for the URL you placed is of different format.
JMX2Graphite can be enhanced to include whitelist/blacklist functionality. You are very welcome to submit a PR - we’ll promise to review it and help you on it.
