### ISSUE TITLE
io.logz.jmx2graphite.TestGraphiteClient > testOnServerShutdown FAILED

### ISSUE THREAD

**Issue by rfalke** [logzio/jmx2graphite#25]
```
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
$ ./gradlew build --debug 
...
17:01:16.346 [DEBUG] [TestEventLogger] Gradle Test Executor 1 STARTED
17:01:16.349 [QUIET] [system.out] 17:01:16.349 [DEBUG] [org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor] Executing test class io.logz.jmx2graphite.TestGraphiteCl
ient
17:01:16.350 [DEBUG] [TestEventLogger] 
17:01:16.350 [DEBUG] [TestEventLogger] io.logz.jmx2graphite.TestGraphiteClient STARTED
17:01:17.032 [DEBUG] [TestEventLogger] 
17:01:17.033 [DEBUG] [TestEventLogger] io.logz.jmx2graphite.TestGraphiteClient > testOnServerRestart STARTED
17:01:17.046 [DEBUG] [TestEventLogger] 
17:01:17.047 [DEBUG] [TestEventLogger] io.logz.jmx2graphite.TestGraphiteClient > testOnServerRestart STANDARD_OUT
17:01:17.047 [DEBUG] [TestEventLogger]     17:01:17.043 [Test worker] INFO  io.logz.jmx2graphite.GraphiteClient - Graphite metrics prefix: bla-service.bla-host_com.
17:01:17.049 [DEBUG] [TestEventLogger]     17:01:17.045 [Test worker] INFO  io.logz.jmx2graphite.GraphiteClient - Graphite Client: using writeTimeoutMs of 20000 [ms]. Establishing c
onnection...
17:01:17.070 [DEBUG] [TestEventLogger]     17:01:17.069 [Test worker] INFO  io.logz.jmx2graphite.TestGraphiteClient - Starting dummy graphite server on port 12329
17:01:17.088 [DEBUG] [TestEventLogger]     17:01:17.088 [Test worker] INFO  io.logz.jmx2graphite.TestGraphiteClient - Shutting down mock graphite server
17:01:17.091 [DEBUG] [TestEventLogger]     17:01:17.090 [Test worker] INFO  io.logz.jmx2graphite.DummyGraphiteServer - Waiting for server to finish shutdown...
17:01:17.091 [DEBUG] [TestEventLogger]     17:01:17.090 [Thread-4] INFO  io.logz.jmx2graphite.DummyGraphiteServer - Client closed connection
17:01:17.091 [DEBUG] [TestEventLogger]     17:01:17.091 [Test worker] INFO  io.logz.jmx2graphite.DummyGraphiteServer - Dummy graphite server closed
17:01:20.094 [DEBUG] [TestEventLogger]     17:01:20.093 [Test worker] INFO  io.logz.jmx2graphite.TestGraphiteClient - Starting dummy graphite server on port 12329
17:01:20.242 [DEBUG] [TestEventLogger] 
17:01:20.242 [DEBUG] [TestEventLogger] io.logz.jmx2graphite.TestGraphiteClient > testOnServerRestart PASSED
17:01:20.243 [DEBUG] [TestEventLogger] 
17:01:20.243 [DEBUG] [TestEventLogger] io.logz.jmx2graphite.TestGraphiteClient > testOnServerShutdown STARTED
17:01:20.245 [DEBUG] [TestEventLogger] 
17:01:20.245 [DEBUG] [TestEventLogger] io.logz.jmx2graphite.TestGraphiteClient > testOnServerShutdown STANDARD_OUT
17:01:20.245 [DEBUG] [TestEventLogger]     17:01:20.242 [Time-limited test] INFO  io.logz.jmx2graphite.GraphiteClient - Graphite metrics prefix: bla-service.bla-host_com.
17:01:20.245 [DEBUG] [TestEventLogger]     17:01:20.243 [Time-limited test] INFO  io.logz.jmx2graphite.GraphiteClient - Graphite Client: using writeTimeoutMs of 2000 [ms]. Establish
ing connection...
17:01:20.246 [DEBUG] [TestEventLogger]     17:01:20.243 [Time-limited test] INFO  io.logz.jmx2graphite.TestGraphiteClient - Starting dummy graphite server on port 48622
17:01:20.248 [DEBUG] [TestEventLogger]     17:01:20.247 [Time-limited test] INFO  io.logz.jmx2graphite.TestGraphiteClient - Shutting down mock graphite server
17:01:20.249 [DEBUG] [TestEventLogger]     17:01:20.248 [Thread-6] INFO  io.logz.jmx2graphite.DummyGraphiteServer - Client closed connection
17:01:20.250 [DEBUG] [TestEventLogger]     17:01:20.248 [Time-limited test] INFO  io.logz.jmx2graphite.DummyGraphiteServer - Waiting for server to finish shutdown...
17:01:20.251 [DEBUG] [TestEventLogger]     17:01:20.248 [Time-limited test] INFO  io.logz.jmx2graphite.DummyGraphiteServer - Dummy graphite server closed
17:01:20.379 [QUIET] [system.out] 17:01:20.379 [INFO] [org.gradle.api.internal.tasks.testing.worker.TestWorker] Gradle Test Executor 1 finished executing tests.
17:01:20.383 [QUIET] [system.out] 17:01:20.382 [DEBUG] [org.gradle.process.internal.child.ActionExecutionWorker] Completed Gradle Test Executor 1.
17:01:20.413 [DEBUG] [TestEventLogger] 
17:01:20.413 [DEBUG] [TestEventLogger] io.logz.jmx2graphite.TestGraphiteClient > testOnServerShutdown FAILED
17:01:20.414 [DEBUG] [TestEventLogger]     java.lang.AssertionError: Send metrics succeeded but server is down
17:01:20.414 [DEBUG] [TestEventLogger]         at org.junit.Assert.fail(Assert.java:88)
17:01:20.414 [DEBUG] [TestEventLogger]         at io.logz.jmx2graphite.TestGraphiteClient.testOnServerShutdown(TestGraphiteClient.java:59)
17:01:20.414 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:01:20.414 [DEBUG] [TestEventLogger]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:01:20.414 [DEBUG] [TestEventLogger]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:01:20.414 [DEBUG] [TestEventLogger]         at java.lang.reflect.Method.invoke(Method.java:498)
17:01:20.414 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
17:01:20.414 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
17:01:20.414 [DEBUG] [TestEventLogger]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
17:01:20.414 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
17:01:20.415 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
17:01:20.416 [DEBUG] [TestEventLogger]         at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
17:01:20.416 [DEBUG] [TestEventLogger]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
17:01:20.416 [DEBUG] [TestEventLogger]         at java.lang.Thread.run(Thread.java:748)
17:01:20.417 [DEBUG] [TestEventLogger] 
17:01:20.417 [DEBUG] [TestEventLogger] io.logz.jmx2graphite.TestGraphiteClient FAILED
17:01:20.417 [QUIET] [system.out] 17:01:20.416 [DEBUG] [org.gradle.process.internal.child.ActionExecutionWorker] Stopping client connection.
17:01:20.417 [DEBUG] [TestEventLogger] 
17:01:20.418 [DEBUG] [TestEventLogger] Gradle Test Executor 1 FAILED
...
```

**Comment by yyyogev** [comment]
Faulty test removed
