### ISSUE TITLE
Coredump when using javagent

### ISSUE THREAD

**Issue by eberkut** [logzio/jmx2graphite#45]
I'm trying to use jmx2graphite 1.2.5 as a javaagent to monitor WildFly. Unfortunately I'm getting an error when starting the service.

  JAVA_OPTS:  -server -ea -Xms1g -Xmx2g -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:SurvivorRatio=4 -XX:+DisableExplicitGC -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dcom.sun.xml.bind.v2.bytecode.ClassTailor.noOptimize=true -javaagent:/opt/wildfly/jmx2graphite-1.2.5-javaagent.jar=GRAPHITE_HOST=X.X.X.X,SERVICE_NAME=wildfly

=========================================================================

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.io.FileNotFoundException: /Users/yogevmets/logzio/jmx2graphite/args (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at java.io.FileWriter.<init>(FileWriter.java:63)
        at io.logz.jmx2graphite.Jmx2GraphiteJavaAgent.premain(Jmx2GraphiteJavaAgent.java:26)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
Aborted (core dumped)

**Comment by yyyogev** [comment]
@eberkut Are you using the jar from the release?

**Comment by yyyogev** [comment]
@eberkut  we issued a new version, please use it instead

**Comment by eberkut** [comment]
Yes I was using the jar from the release. I can confirm the issue is resolved by using 1.3. Thanks for the quick reply.

**Comment by yyyogev** [comment]
You welcome
Thanks for raising it up!
